### A vanilla LSTM using PyTorch

Import packages:

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [33]:
# Seed.
torch.manual_seed(1)

Define LSTM:

In [5]:
# Input dim is 3, output dim is 3.
lstm = nn.LSTM(3, 3)

In [38]:
# Make a sequence of length 5.
inputs = [torch.randn(1, 3) for _ in range(5)]
inputs

[tensor([[-2.5667, -1.4303,  0.5009]]),
 tensor([[ 0.5438, -0.4057,  1.1341]]),
 tensor([[-1.1115,  0.3501, -0.7703]]),
 tensor([[-0.1473,  0.6272,  1.0935]]),
 tensor([[ 0.0939,  1.2381, -1.3459]])]

In [40]:
# Initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
hidden

(tensor([[[ 0.0554,  1.1340, -0.5326]]]),
 tensor([[[ 0.6592, -1.5964, -0.3769]]]))

In [41]:
for i in inputs:
    # Step through the sequence, one element at a time.
    # After each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)